### ISSUE TITLE
IMGEGLImage is not consistent

### ISSUE THREAD

**Issue by HuongNTY** [Apparence-io/CamerAwesome#120]
## Steps to Reproduce

* When take picture but can't take picture,  problem is 'IsTextureConsistent: IMGEGLImage is not consistent'.  *

## Expected results
*I wish I could take pictures on this device *

| Lenovo| Lenovo TB-8505X| Android 10        |

</details>

**Comment by istornz** [comment]
Closed, please reopen if this bug occurs on latest stable v1.0.0
