### ISSUE TITLE
How to capture video from multiple cameras at the same time?

### ISSUE THREAD

**Issue by aytunch** [Apparence-io/CamerAwesome#131]
## Proposal

Recently, I see many social apps which can capture and save video from both cameras at the same time. 
_I can show my surroundings using the back camera and in a small PIP layout, I can show myself._

What needs to be done to accomplish this without losing fps and resolution?

- Can we record with both cameras at the same time and use ffmpeg to combine 2 videos?
- Can we use image streams from both cameras at the same time to overlay them on each other?

Are there any blockers for this functionality in Flutter?

@g-apparence are you going to continue implementing this awesome package btw? Google's camera package lacks a lot of features.

EDIT: here iOS native implementations on Multi Camera Capture (Gautier shared the Android link in the below comment):
https://www.wwdcnotes.com/notes/wwdc19/249/

<img width="331" alt="Screen Shot 2022-05-07 at 12 24 27" src="https://user-images.githubusercontent.com/6442915/167248101-54381515-3ce4-4d0e-b692-fb8379c4c22c.png">

**Comment by g-apparence** [comment]
Thank you for this really nice idea. 
Didn't know some apps do that nowadays. 
Did you see that on Android devices ?

I don't think using ffmpeg is the best solution. Processing a live video seems a bit overengineering at first sight. 
I think you can simply use multiple texture. 
Thing is, I don't think this is doable on all devices. The new multi camera hardware seems to open many doors. 
https://developer.android.com/training/camera2/multiple-camera-streams-simultaneously

I'm searching some times to work on this. I hope summer will let me some time. 
I would love to investigate more on the cameraX implementation. 
(having a baby and a startup ain't letting much times...)

**Comment by aytunch** [comment]
I am glad that you find this use-case worthy
There are similar issues on the camera package but it seems like Flutter engineers won't be implementing it anytime soon.
https://github.com/flutter/flutter/issues/51928#issuecomment-1120289524
Can't wait for this exciting feature.
Also congratulations on the newborn :)

**Comment by istornz** [comment]
We released beta of multi camera feature with the v2.
You can test it right now 👍

**Comment by aytunch** [comment]
Great news @istornz 
You people are Awesome :)
