### ISSUE TITLE
README typos?

### ISSUE THREAD

**Issue by Correct-Syntax** [Apparence-io/CamerAwesome#170]
![image](https://user-images.githubusercontent.com/60711001/208313858-49b9f553-019a-4086-ae9c-836cfe39a34c.png)

Hey, nice project. The image in the README appears to have a few typos. 

"camerAwesome" -> "cameraAwesome"
"beautifull" -> "beautiful"

There are other places in the README where "camerAwesome" is used and other places where "cameraAwesome" is used, etc. I believe it should be the latter.

![image](https://user-images.githubusercontent.com/60711001/208313991-e29d1d16-1a48-476b-8c06-e1e6478c5e3f.png)

**Comment by g-apparence** [comment]
Hey,
totally we finally found an internal agreement on camerAwesome ! 

We fixed the source code according to this. 
Let's fix the Readme too (as we worked on a more complete documentation, the readme will be reworked to just the minimum).

**Comment by apalala-dev** [comment]
Typos have been fixed a while ago, feel free to open an issue if you find new ones 👍
