### ISSUE TITLE
doc link give 404

### ISSUE THREAD

**Issue by azazadev** [Apparence-io/CamerAwesome#205]
thanks and congratulations for this 1.0.0-rc1 release ! awesome !!!

small doc update : 

go to https://docs.page/Apparence-io/camera_awesome/getting_started/awesome-ui#-need-more-customization-

**See docs** give 404

**Comment by g-apparence** [comment]
Thank you 👍
That seems to have been an error of docs.page that provides it. 
This seems working now. 

Sorry for this, I close.
