### ISSUE TITLE
how do i convert camera frame to opencv Mat in c++ using dart ffi

### ISSUE THREAD

**Issue by aavinashj** [Apparence-io/CamerAwesome#223]
I need to run custom analysis and Im using Datr ffi, Im able to convert the frames in the official camera package by converting yuv planes to Mat but the same does not work for this package

**Comment by chaoyifei** [comment]
@aavinashj  how do you solve this pr， I want to use tflite，and need  to  convert the frames in the official camera package by converting yuv planes, but  return Incorrect result

tflite

https://pub.dev/packages/tflite

```
var recognitions = await Tflite.detectObjectOnFrame(
  bytesList: img.planes.map((plane) {return plane.bytes;}).toList(),// required
  model: "SSDMobileNet",  
  imageHeight: img.height,
  imageWidth: img.width,
  imageMean: 127.5,   // defaults to 127.5
  imageStd: 127.5,    // defaults to 127.5
  rotation: 90,       // defaults to 90, Android only
  numResults: 2,      // defaults to 5
  threshold: 0.1,     // defaults to 0.1
  asynch: true        // defaults to true
);
```

camerAwesome
```
imageAnalysisConfig: AnalysisConfig(
          androidOptions: const AndroidAnalysisOptions.yuv420(
            width: 150,
          ),
```
Is there any difference between these two camera stream?
camera_plugin works well

@apalala-dev
