### ISSUE TITLE
Outdated image package version dependency

### ISSUE THREAD

**Issue by talamaska** [Apparence-io/CamerAwesome#238]
## Steps to Reproduce

install latest camerawesome
try to install latest crop_your_image

## Expected results

no package version conflicts should be observed

## Actual results
```
Because crop_your_image >=0.7.4 depends on image ^4.0.6 and camerawesome 1.2.0 depends on image ^3.3.0, crop_your_image >=0.7.4 is incompatible with camerawesome 1.2.0.
And because no versions of camerawesome match >1.2.0 <2.0.0, crop_your_image >=0.7.4 is incompatible with camerawesome ^1.2.0.
So, because giftmate depends on both camerawesome ^1.2.0 and crop_your_image ^0.7.4, version solving failed.
pub get failed
```
## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A53*  | *Android 13*  |

Please update the image package dependency so we can use other packages that depend on more recent version of it

**Comment by g-apparence** [comment]
thank you reporting it. 
In the meantime you can override this adding this in your pubspec.yaml :
```yaml
dependency_overrides:
    image: ^4.0.6
```

See : https://dart.dev/tools/pub/dependencies#dependency-overrides
