### ISSUE TITLE
Question: How to Run Code after picture is taken or video is finished recording

### ISSUE THREAD

**Issue by chitgoks** [Apparence-io/CamerAwesome#240]
I already have a code in place to run the code what to do with the picture or video taken. But i am not sure where this takes place.

I figured it would be in 

```
saveConfig: SaveConfig.photoAndVideo(
                            photoPathBuilder: () => _path(CaptureMode.photo),
                            videoPathBuilder: () => _path(CaptureMode.video),
                            initialCaptureMode: CaptureMode.photo,
                          ),
```

but  that sample just returns a string. what would the photoPathBuilder look like if i would place code after a picture is taken (or video)?

Thoughts?

**Comment by apalala-dev** [comment]
The SaveConfig does not provide a callback to call after a media has been saved.

However, you can listen to `cameraState.captureState$` to react to different capture states. A new event is provided whenever the status of the capture status changes, including when a media is saved.
Here, you probably want a `MediaCapture` with a `MediaCaptureStatus.success` before running your code.

**Comment by chitgoks** [comment]
Thanks! I think that is what I am looking for.

**Comment by rlee1990** [comment]
@apalala-dev how do you do this?

> The SaveConfig does not provide a callback to call after a media has been saved.
> 
> However, you can listen to `cameraState.captureState$` to react to different capture states. A new event is provided whenever the status of the capture status changes, including when a media is saved. Here, you probably want a `MediaCapture` with a `MediaCaptureStatus.success` before running your code.

**Comment by jasonroland** [comment]
Here's how im doing this (I am using riverpod) this seems overly complicated.
`return CameraAwesomeBuilder.awesome(
            saveConfig: SaveConfig.photo(),
            onMediaTap: (mediaCapture) {
              print("tapped");
            },
            topActionsBuilder: (state) {
              //this only written here bec have state here, prolly should go somewhere else tbh
              _captureStateSubscription ??=
                  state.captureState$.listen((MediaCapture? mediaCapture) {
                if (mediaCapture != null) {
                  capture = mediaCapture;

                  switch (mediaCapture.status) {
                    case MediaCaptureStatus.success:
                      //image captured, do some code like get the file path
                      print("Image captured: ${filePath(mediaCapture)}");
                      break;
                    case MediaCaptureStatus.capturing:
                      print("Capturing in progress...");
                      break;
                    case MediaCaptureStatus.failure:
                      print("Capture failed!");
                      break;
                  }
                }
              });

    //here is how you can get file path
    String filePath(MediaCapture mediaCapture) {
      if (mediaCapture.status == MediaCaptureStatus.success &&
          mediaCapture.captureRequest != null) {
        return mediaCapture.captureRequest.when(
           single: (single) => single.file!.path,
          multiple: (multiple) => multiple.fileBySensor.values.first!.path,
        );
      } else {
        return "null found";
      }
    }
`
