### ISSUE TITLE
On iOS, the library tries to access the microphone in photo capture mode with enableAudio set to false

### ISSUE THREAD

**Issue by valorbyte** [Apparence-io/CamerAwesome#247]
## Steps to Reproduce

I build the UI like this:

<code>
CameraAwesomeBuilder.custom(
        initialCaptureMode: CaptureMode.photo,
        enableAudio: false,
        sensor: Sensors.back,
        previewFit: CameraPreviewFit.cover,
        exifPreferences: ExifPreferences(saveGPSLocation: false),
        flashMode: _isFlashMode ? FlashMode.on : FlashMode.none,
        saveConfig: SaveConfig.photo(
          pathBuilder: _imageService.requestTemporaryImageFilePath,
        ),
        builder: (
          CameraState state,
          PreviewSize previewSize,
          Rect previewRect,
        )
{
....
}
</code>

## Expected results

When in photo-only mode with enableAudio set to false, the permission should not be asked.

## Actual results

The app crashes with the following message as soon as the camera view is opened:

This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

As a sidenote, I have no issues with this on Android even though I don't have the equivalent permissions set in the manifest.

## About your device

| Brand   | Model             | OS            |
| ------- | --------------| --------- |
| Apple  | iPhone 14 Pro  | 16.2         |

## Your flutter version

Run this in your command line 
Flutter 3.7.0 • channel stable

</details>

**Comment by valorbyte** [comment]
Ok, also it seems it does not make a difference even if I use the default builder.

**Comment by apalala-dev** [comment]
I can reproduce the issue, thanks for reporting 👍
