### ISSUE TITLE
On Image/Video Capture

### ISSUE THREAD

**Issue by rlee1990** [Apparence-io/CamerAwesome#251]
It would be nice to have an option that when you take an image or video capture we could get the file path and pop the route. As of now i would have to use the onMediaTap function.

**Comment by g-apparence** [comment]
That's right. 
Thank you suggesting it. 

If you are interested in contributing, we're fully opened to help you doing it.

**Comment by rlee1990** [comment]
@g-apparence thinks. I'll try to find some time to see what I can do to help. For now Ill use the workaround thanks.
