### ISSUE TITLE
Selfies are flipped

### ISSUE THREAD

**Issue by migalv** [Apparence-io/CamerAwesome#255]
## Steps to Reproduce

1. Download the CamerAwesome example
2. Install and run the app
3. Take a picture in selfie mode
4. Check output

## Expected results

In my opinion, when taking pictures in selfie mode they should always be mirrored as this is the expected behavior by 99% of users.

Here is an example from Instagram:

<details>
<summary>Instagram</summary>
<br>
<video src="https://user-images.githubusercontent.com/31893180/221919503-11e5671a-bcfc-4e78-9be0-ff4cef3730f0.mp4"/>
</details>

## Actual results

The image is flipped and generates a strange sensation.

Example from CamerAwesome example code:

<details>
<summary>CamerAwesome</summary>
<br>
<video src="https://user-images.githubusercontent.com/31893180/221918991-437d8d3d-e0e0-4cd5-9816-b397b6f38702.mp4"/>
</details>

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Huawei* | *Huawei P30*  | *EMUI 12.0.0*  |

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.2 22D49 darwin-arm, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by g-apparence** [comment]
Yes you're right. 
Added the enhancement label

**Comment by istornz** [comment]
We tested on latest iPhone 14 & on 3 Android devices (2 new, 1 old).

Only the old Android device (Huawei) did not perform a flip on the Selfie, all others do a Flip. So we think it's a manufacturer choice but in the major case it seems flip the selfie image is the best way to display a selfie image.

**Comment by apalala-dev** [comment]
On the native camera app of my Xiaomi Mi 9T, the picture taken is mirrored like expected from @migalv.
After searching in the settings of the app, I found an option to set front camera pictures to be mirrored or not. Not sure if it was enabled by default or if I've set it manually.
Overall, it seems to be an user/manufacturer choice, we should probably give an option to control it rather than expect a behaviour to be the right one for every one

**Comment by migalv** [comment]
I agree with @apalala-dev. This seems to be a users/manufacturer's choice. So if you allow the developer to choose the expected behavior for their app it would be a really good improvement.

**Comment by istornz** [comment]
Yeah of course, we can expose an option to flip the selfie or not !

On the Android side @apalala-dev did you flip the image manually ? I'm just worried about the flip was done on the cameraX part and AVCapture side ?

**Comment by apalala-dev** [comment]
I don't think there is any handmade flip made on the Android part.
I am not sure if it can be done directly by CameraX (with a setting or something like that).
The more problematic on the Android side is that I don't know if the image is flipped or not which means I don't know if the image needs to be flipped or not 😕 I hope that CameraX is consistent and is always flipped (or not flipped)...

**Comment by apalala-dev** [comment]
It's easier than expected on Android:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/6177464/225952294-b22acd65-5471-4179-92b9-29fc5f7198a0.png">
You might have something similar on the iOS part @istornz ?

**Comment by apalala-dev** [comment]
Apparently this is a feature quite demanded on the official plugin:
https://github.com/flutter/flutter/issues/27650

We might get an other reason to implement it! 👀

**Comment by istornz** [comment]
@apalala-dev Yeah very easy on the iOS side too, we just need to remove the first condition 👍 
It's a good idea to implement it !

![Capture d’écran 2023-03-17 à 17 12 44](https://user-images.githubusercontent.com/16645312/225959777-d9d48134-9834-40c9-a78d-c405aae2f3d4.png)

**Comment by migalv** [comment]
> Apparently this is a feature quite demanded on the official plugin: [flutter/flutter#27650](https://github.com/flutter/flutter/issues/27650)
> 
> We might get an other reason to implement it! 👀

That's exactly right @apalala-dev 

You guys are amazing! Let's go

**Comment by istornz** [comment]
Hi @migalv, I created a new PR to implement this feature on **Dart** & **iOS** sides #278.
@apalala-dev will implement the Android part asap 👍
