### ISSUE TITLE
Landscape recording saves the video as portait on iOS

### ISSUE THREAD

**Issue by Aldaniee** [Apparence-io/CamerAwesome#259]
## Steps to Reproduce

1. Set the home page of the example app to `CustomUiExample3()`
2. Build to an iOS device
3. Rotate your phone 90 degrees so it is in landscape orientation and record a video
4. Tap the recorded video to play it back or export the file

## Expected results

The video is saved in the same landscape orientation that it was recorded in.

## Actual results
The video is saved in portrait orientation.

## About your device

| Brand   | Model                    | OS        |
| ------- | ----------------- | -------- |
| *Apple* | *iPhone 12 Pro*  | *16.3.1*  |

## Your flutter version

Flutter 3.7.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b4bce91dd0 (10 days ago) • 2023-02-21 09:50:50 +0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

</details>

**Comment by g-apparence** [comment]
Thank you reporting it.

**Comment by WindBise** [comment]
This issue still exist in 2.3.0, any updates?

**Comment by WindBise** [comment]
> I found if rotation is locked in iphone, the issue persists. However if rotation is not locked， the video saved will be landscape as expect.

Now the issue persists whether rotation is locked or not .
