### ISSUE TITLE
Proposal : imageAnalysisOnly mode

### ISSUE THREAD

**Issue by g-apparence** [Apparence-io/CamerAwesome#271]
## Context
Today when you want to only use analysis camerAwesome requires to provide save configuration and other useless stuff. 

## Proposal
Adding an AnalysisOnly factory that not requires those useless options and is focused on anlysis. 
You should optionnaly still have options for 
- flash on / off
- switch camera
- preview fit 

No access file permission required.

**Comment by M123-dev** [comment]
Especially the permission to access files should be made optional if you don't plan to save images or videos

**Comment by g-apparence** [comment]
> Especially the permission to access files should be made optional if you don't plan to save images or videos 

I add this.
Thank you for the idea

**Comment by apalala-dev** [comment]
✅ Feature included in 1.4.0 (See `CameraAwesomeBuilder.analysisOnly()`)
