### ISSUE TITLE
Theme/Awesometheme not available

### ISSUE THREAD

**Issue by EggsAreUs** [Apparence-io/CamerAwesome#281]
## Steps to Reproduce

Documentation describes Themes but don't appear to be available within either 'CameraAwesomeBuilder.awesome(' or 'CameraAwesomeBuilder.custom(' constructors.

Tried implementing using the basic example in order to rule out conflicts etc, from:
https://github.com/Apparence-io/CamerAwesome/blob/master/example/lib/custom_theme.dart

Similarly with topActionsBuilder, middleContentBuilder and bottomActionsBuilder, none of which seem to be available.

Updated build.gradle with compileSdkVersion 33
But assuming that this may not be a factor as error occurs before getting to build stage.

## Expected results

Options to customise buttons, interface etc.

## Actual results

Error in IDE showing 'theme' parameter not defined.
Similar with middleContentBuilder, topActionsBuilder and bottomActionsBuilder.

## About your device

Unable to run on device at present as error in IDE.

## Your flutter version

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (3 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

I'm new to GitHub so hope this is correct place to log this.
Great plugin CamerAwesome which seems to overcome some issues with other camera plugins. Also easy to implement and otherwise running well. 
Thank you.

**Comment by apalala-dev** [comment]
I just tried to run the custom_theme example on my computer on master after a git pull and it seems to work.

Are you using latest version of master channel?

**Comment by EggsAreUs** [comment]
I was using 1.2.1 from flutter pub add... but now accessing from git master direct in pubspec.yaml.
(Guess 1.3.0 not published)
Working now.
Thanks for your help.
