### ISSUE TITLE
No top, middle and bottom builder.

### ISSUE THREAD

**Issue by M3LevLjo** [Apparence-io/CamerAwesome#283]
can't seem to find 

-  topActionsBuilder
-  middleContentBuilder
-  bottomActionsBuilder

though by looking at [the docs](https://docs.page/Apparence-io/camera_awesome/getting_started/awesome-ui#place-widgets-in-your-ui) it should be there. 

![image](https://user-images.githubusercontent.com/112752435/226855227-ba74af0a-04e6-42a8-bf74-2c3a8ca3fe18.png)

![image](https://user-images.githubusercontent.com/112752435/226855982-2f91fc7c-fa8c-4180-b916-a4cfe002b4a8.png)

am I missing something?

**Comment by apalala-dev** [comment]
The doc is based on 1.3 release but we delayed the release since there was a bug with image filters.

We just released the fix (#284) so hopefully we can publish 1.3 soon 👍

**Comment by apalala-dev** [comment]
We've [released the 1.3](https://pub.dev/packages/camerawesome), you should be access the properties mentioned in the docs now.

Closing since it should be fixed, but feel free to reopen if not.
