### ISSUE TITLE
[IOS] Only Photo and Video CaptureModes available 

### ISSUE THREAD

**Issue by BenoitOutman** [Apparence-io/CamerAwesome#314]
Hi, on IOS, CaptureModes has only PHOTO and VIDEO modes

so when using previewOnly or analysis cause ios to ask for mic permission:

Cause:

in CamerawesomePlugin.m -> setCaptureMode"Mode" function:

 CaptureModes captureMode = ([mode isEqualToString:@"PHOTO"]) ? Photo : Video;

Preview and analysis_only are considered as Video mode.

**Comment by istornz** [comment]
This is now fixed & releaded on prerelease 2
