### ISSUE TITLE
Be able to customise multi cam preview style

### ISSUE THREAD

**Issue by lei-cao** [Apparence-io/CamerAwesome#334]
## Proposal
I am testing the multi cam feature, in the initial layout of the preview, the mini cam floating window is at the bottom left of the screen. I want to be able to change the floating window initial position, as well as I need to change the size and style of the floating window.
Not sure if it's already supported, I didn't find the document.

Thank you so much

*Describe your new feature*
- support customise the floating window, size, position, style.

**Comment by apalala-dev** [comment]
We pre-released the 2.0.0 version. You can find it [here](https://pub.dev/packages/camerawesome/versions/2.0.0-dev.1).
It includes more customization on the picture-in-picture preview.
I'll close the issue as it's now implemented. If anything more specific is still lacking, feel free to create a new issue. 👍
