### ISSUE TITLE
iOS app crashes when Microphone description is not added to Info.plist

### ISSUE THREAD

**Issue by vlazdra** [Apparence-io/CamerAwesome#335]
## Steps to Reproduce

Just took an example from your website, to implement the scanning of QR codes.
For some reason the app crashes when the Microphone Info.plist key is not added.

```
CameraAwesomeBuilder.previewOnly(
    // 2.
    imageAnalysisConfig: AnalysisConfig(
      androidOptions: const AndroidAnalysisOptions.nv21(
        width: 1024,
      ),
      maxFramesPerSecond: 5,
      autoStart: true,
    ),
    // 3.
    onImageForAnalysis: (img) => _processImageBarcode(img),
    // 4.
    builder: (cameraModeState, previewSize, previewRect) {
      // return _BarcodeDisplayWidget(
      //   barcodesStream: _barcodesStream,
      //   scrollController: _scrollController,
      //   // 5.
      //   analysisController: cameraModeState.analysisController!,
      // );
      return const SizedBox.shrink();
    },
  )
```

## Expected results

The app doesn't crash when the previewOnly mode is used and Microphone description key is not added to Info.plist

## Actual results

App crashes when the Microphone description key is not added.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone Xr*  | *16.4.1*  |

## Your flutter version
<details>
Run this in your command line 
```flutter --version```

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

</details>

**Comment by vlazdra** [comment]
Just to add, I'm using the latest version 1.4.0

**Comment by vlazdra** [comment]
@apalala-dev Hey, would be able to share an ETA of when this would be fixed?

**Comment by vlazdra** [comment]
Connected to #176

**Comment by istornz** [comment]
Prerelease 2 is now released!

**Comment by vlazdra** [comment]
Will give it a go and check back and close if it no longer asks for microphone permission in preview only mode. Thanks! 🙌
