### ISSUE TITLE
advanced camera features

### ISSUE THREAD

**Issue by jamesdixon** [Apparence-io/CamerAwesome#35]
Hello!

Not an issue or really a feature request but more about determining what's possible.

I haven't seen any camera apps outside of the native camera interface that can take advantage of things like different camera lenses (such as on the iPhone 12). Do you guys know if it's possible to access these features? In a perfect world, I'd love to just get access to the full-featured native camera interface but that doesn't seem possible (at least on iOS).

I did come across this example: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/avcam_building_a_camera_app

Would love to hear your thoughts!

**Comment by g-apparence** [comment]
Hello James,
Thank you for opening this discussion. 
If you speak about switching rear and front camera we do that but I'm not sure about your question.
iOS is high level and most of the process is hidden from the API while Android is very low level (too much). 
If I understand it correctly you want to access things like :  [builtintriplecamera](https://developer.apple.com/documentation/avfoundation/avcapturedevice/devicetype/3377621-builtintriplecamera)

Flutter is for both Android and iOS we try to make things work the same on both platforms.
So we tend to not add specific interfaces from one of each to not confuse people. But camera lenses are now more complex and maybe we gonna have to add these to the device sensors list like "FRONT" and "BACK".

**Comment by jamesdixon** [comment]
@g-apparence hello!

Yes, being able to access different lenses is definitely at the top of my list when it comes to advanced features.

One thing I hear from many users with our current camera implementation is that they end up taking pictures outside of our app and importing them so they can take advantage of those features, such as different lenses.

**Comment by jamesdixon** [comment]
@g-apparence hello! I hope all is well. 

I was curious if support for accessing different camera lenses (telephoto, wide angle) are supported in the 1.x version?

**Comment by apalala-dev** [comment]
Hello @jamesdixon 
CamerAwesome doesn't provide this feature yet in 1.x.

I tried to add this feature to the Android side a few days ago but it is (unfortunately) not as easy as it seems.
Depending on the device, the Android version and wether your app is whitelisted or not, third party apps may only have access to the "main" camera sensor.
On my Xiaomi Mi 9T for instance, I have only one back camera in third party apps (like Open Camera) and 3 on the preinstalled camera app.

On iOS, it seems _doable_.

Development of this feature will probably depend on when we can access compatible devices to test it.

**Comment by istornz** [comment]
Closing this issue, please follow #195 now 👍
