### ISSUE TITLE
google_mlkit_commons introduced breaking changes

### ISSUE THREAD

**Issue by vlazdra** [Apparence-io/CamerAwesome#355]
## Steps to Reproduce

Just follow the instructions for converting the AnalasysImage to InputImage by using the latest version of `google_mlkit_barcode_scanning 0.7.0`

## Expected results

The code should work.

## Actual results

Some classes have been removed from the core library.

Here is the `google_mlkit_commons` Changelog: https://pub.dev/packages/google_mlkit_commons/changelog

**Comment by g-apparence** [comment]
Nice ! 
Thank you reporting this.
If you are interested on working on this, this would be a pleasure.

**Comment by iBog** [comment]
Added my PR to fix this
