### ISSUE TITLE
[Question] Stream video and analysis mode in background

### ISSUE THREAD

**Issue by scalz** [Apparence-io/CamerAwesome#360]
## Proposal
Hello,

I've not digged/tried all your features yet, but would it be doable to implement this usecase with CamerAwesome, **for Android only in background mode, not terminated**:
- on a wall mounted tablet for instance, camera would detect if there is motion (with analysis mode??), then custom logic would power on screen or send a msg to a server, 
- and also stream camera video to a local server?

(without having to display camera widget)

Thank you for sharing with us your awesome work, this is a really nice package!

**Comment by g-apparence** [comment]
I don't really think it's a camerAwesome case. 
CamerAwesome only helps to integrate better camera experience within apps. 
If you want to play with motion sensors or without preview this is out of this plugin scope. 

What you try to do is totally doable with some custom code with platform channels. 
Also thank you for your kind comment. We try to not solve all problem and focus on a camera interface that is really simple to use within apps.
