### ISSUE TITLE
Box constraints problem using example code in README

### ISSUE THREAD

**Issue by kyeshmz** [Apparence-io/CamerAwesome#388]
## Steps to Reproduce

*Describe how to reproduce the error*

Create a page using the example code. 
Removing preview fit does not solve the problem.

```
 return Scaffold(
      // appBar: AppBar(),
      body: CameraAwesomeBuilder.awesome(
        previewFit: CameraPreviewFit.fitWidth,
        saveConfig: SaveConfig.photoAndVideo(),
        onMediaTap: (mediaCapture) {
          // OpenFile.open(mediaCapture.filePath);
        },
      ),
```

## Expected results

*What it should be*
Some kind of preview, I suppose.

## Actual results

*What you see*
<img width="391" alt="Screenshot 2023-08-30 at 11 14 59 AM" src="https://github.com/Apparence-io/CamerAwesome/assets/12763472/be096fba-6b9d-4a34-bc56-6109ff5e7cb3">

## About your device

IS A SIMULATOR
| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Google* | *Pixel 6A*  | *13*  |

## Your flutter version

Run this in your command line 
```flutter --version```

*Paste the result here*
Flutter 3.13.0 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (2 weeks ago) • 2023-08-15
21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

</details>

**Comment by kyeshmz** [comment]
So it seems like clicking the 4:3 renders this problem out, something to do with the initial settings?

**Comment by g-apparence** [comment]
This was a problem with the previous preview implementation. 
This should now be fixed. 
Feel free to reopen this if needed
