### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by zychns** [Apparence-io/CamerAwesome#391]
Hi, 
The plugin looks great but I'm struggling big time to just make it to work out of the box. The documentation and the latest version I'm using are not the same :| Am I the only one having an issue with properly configuring it?
The documentation says that for saveConfig and simple photo taking I just need: saveConfig: SaveConfig.photo(), but pathBuilder: is required in here and there is nothing about it in the documentation. I have checked github and the dedicated site to that plugging and still cannot find the answer on how to get it to work "out of the box." Any help would be appreciated. Thank You

**Comment by azazadev** [comment]
for 2.0.0-dev.1

`saveConfig: SaveConfig.photoAndVideo()`

for 1.4.0

      saveConfig: SaveConfig.photoAndVideo(
        photoPathBuilder: () async {
          return "some/path.jpg";
        },
        videoPathBuilder: () async {
          return "some/path.mp4";
        },
      ),

an agree with you the documentation is for new dev version 2.0.0-dev.1, no more doc for stable version 1.4.0

**Comment by g-apparence** [comment]
Sorry for this. The 2.0.0 will be released soon.
