### ISSUE TITLE
Animation affect while taking photo

### ISSUE THREAD

**Issue by slkmikhail** [Apparence-io/CamerAwesome#398]
Hi there!

I'd like to use camera shutter effect while taking photo.

I didn't find any API to make it. Theoretically, I can add the affect after catching MediaCaptureStatus.capturing. But I have the access to PreviewSize, Rect objects only in that place.

Is there any feature for that? if not, It might be great to see it as soon as possible. 

Thanks!

**Comment by g-apparence** [comment]
You can now have access to the preview size etc directly from the builder now

```dart
CameraAwesomeBuilder.previewOnly(
  builder: (cameraModeState, preview) { // <- here
  },
)
```

(As this is the last work in progress for the 2.0.0 you can use it directly targetting the git repository for now).

**Comment by slkmikhail** [comment]
Thanks for your suggestion,  I've already found a solution to animate sizeBox placed under camera preview based on previewRect' size.

**Comment by g-apparence** [comment]
Ok then I close this issue
