### ISSUE TITLE
[CameraAwesomeBuilder.custom] How to switch camera mode with custom UI ?

### ISSUE THREAD

**Issue by delfme** [Apparence-io/CamerAwesome#406]
I'm looking at official examples about `CameraAwesomeBuilder.custom` and they showcase a single camera mode (either photo or video). How toggling camera mode should be implemented?

The requirement is common one: we have a selector and when user sets it to video we must switch the camera mode from photo to video, or vice-versa. Is it a sample code available for that?
Thx.

**Comment by g-apparence** [comment]
Hi, 

You can check on how it works on the awesome builder that provides a complete UI. 
https://github.com/Apparence-io/CamerAwesome/blob/master/lib/src/widgets/layout/awesome_bottom_actions.dart
I think this should help you.

**Comment by delfme** [comment]
Thx @g-apparence, can it be shared here a class with two `GestureDetector` (for `Text` "photo", "video") which switch camera mode on tap? No need for a complex UI. We already have our UI put up. As long as we get how to switch camera mode, we can connect it in little time.

**Comment by g-apparence** [comment]
I'm a bit out of time this days sorry. 

You can check the awesome widget as it contains everything you need to do this. 
Basically you can ask the state to switch the mode as you want for you. 
Tell me if you don't understand something.
