### ISSUE TITLE
Problems taking photo

### ISSUE THREAD

**Issue by nene147** [Apparence-io/CamerAwesome#412]
When I take a photo in 4:3, it is rotated 90 degrees.
Alternatively, is there a way to take a photo fixed at 3:4 in the forward direction?

**Comment by nene147** [comment]
It was a save-related code issue!

**Comment by nene147** [comment]
It was a save-related code issue!

**Comment by dragongesa** [comment]
> It was a save-related code issue!

what do you mean? i have this issue on samsung devices. Can you share your solution?
