### ISSUE TITLE
Wrong ratio, no padding on the last version 2.0.0+1

### ISSUE THREAD

**Issue by slkmikhail** [Apparence-io/CamerAwesome#416]
## Steps to Reproduce

```
  @override
  Widget build(BuildContext context) {
    return CameraAwesomeBuilder.custom(
      sensorConfig: SensorConfig.single(aspectRatio: CameraAspectRatios.ratio_1_1),
      saveConfig: SaveConfig.photo(mirrorFrontCamera: true),
      enablePhysicalButton: true,
      previewAlignment: Alignment.topCenter,
      previewFit: CameraPreviewFit.fitWidth,
      previewPadding: const EdgeInsets.symmetric(horizontal: 16),
      progressIndicator: const CameraProgressIndicator(),
      builder: (cameraState, cameraPreview) {
        return cameraState.when(
          onPreparingCamera: (_) => const CameraProgressIndicator(),
          onPhotoMode: (photoCameraState) {
            return widget.actionsLayoutBuilder(photoCameraState, cameraPreview);
          },
        );
      },
    );
  }
```

## Expected results

Camera preview ratio must be ratio_1_1
Camera preview padding must be 16 by horizontal

Everything was ok on the dev version - **^2.0.0-dev.1**
![2023-11-24](https://github.com/Apparence-io/CamerAwesome/assets/21338924/17ed2c69-7b77-4917-9db7-9c04d895e068)

## Actual results

ratio 4:3, no padding
<img width="251" alt="image" src="https://github.com/Apparence-io/CamerAwesome/assets/21338924/f9c67e95-d59f-4e34-b104-999083b74734">

## About your device

android any

## Your flutter version

Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (4 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

**Comment by g-apparence** [comment]
Ok padding has been forgotten in the last rework. 
Will fix that

**Comment by slkmikhail** [comment]
> Ok padding has been forgotten in the last rework. Will fix that

What about ration 1:1, are you gonna fix it?

FYI
**enablePhysicalButton: true** - doesn't work at least Samsung devices

**Comment by ZYLIM0702** [comment]
Yes, i faced this issue too and also the preview is always align to the top and even change ratio, the preview still the same. Any solution ?

**Comment by g-apparence** [comment]
> > Ok padding has been forgotten in the last rework. Will fix that
> 
> What about ratio 1:1, are you gonna fix it?

Yes; ratio 1:1 is actually not existing on Android and iOS. 
So we have to crop when you select it. 
Will fix that.

**Comment by dgigantino** [comment]
Any chance to see this fixed, or maybe a workaround in the meanwhile? I'm facing the same issue with padding.

**Comment by g-apparence** [comment]
This has been fixed. #431

**Comment by AlexPopaUpcode** [comment]
the padding is still not working
