### ISSUE TITLE
previewAlignment not working

### ISSUE THREAD

**Issue by michaelgaultjr** [Apparence-io/CamerAwesome#420]
## Steps to Reproduce (version: 2.0.0+1)

Create a CameraAwesomeBuilder widget with `CameraAwesomeBuilder.awesome`, `CameraAwesomeBuilder.custom`, etc... and set the following fields in the widget constructor (as well as any other required fields)
```
previewAlignment: Alignment.center,
previewFit: CameraPreviewFit.contain,
sensorConfig: SensorConfig.single(
  sensor: Sensor.position(SensorPosition.back),
  aspectRatio: CameraAspectRatios.ratio_1_1,
),
```

## Expected results

Camera preview should be centered with space above and below

## Actual results

Camera preview is always on the top of the screen regardless of the value in the `previewAlignment` field

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 12*  | *17.1.2*  |

## Your flutter version

Run this in your command line 
```flutter --version```

3.13.7-0.0.pre.1

</details>

**Comment by g-apparence** [comment]
Yes this has been reported last week. 
I should be able to fix this next week.

**Comment by cooaer** [comment]
Has the issue been fixed？

**Comment by romain-pattyn** [comment]
Is someone working on this issue currently?

**Comment by KnifeLemon** [comment]
#431 fixed

**Comment by g-apparence** [comment]
Thanks for your help @KnifeLemon 🙏🏻
#431 Fixed this
