### ISSUE TITLE
Automatic flash malfunction on Android 13

### ISSUE THREAD

**Issue by Lonely-shang** [Apparence-io/CamerAwesome#422]
## Steps to Reproduce

*Turn on the automatic flash. The flash will still turn on when taking photos during the day*

## Expected results

*Not turning on the flash during the day*

## Actual results

*Flash will be turned on in any scene*

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *vivo* | *vivo Y35*  | *Android 13*  |

## Your flutter version

Run this in your command line 
```flutter --version```

*Flutter 3.13.2 • channel [user-branch] • unknown source
Framework • revision ff5b5b5fa6 (4 months ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0*

</details>

**Comment by g-apparence** [comment]
Hi, 
We made many tests on this but maybe you are right. 
Could you make the same test in the same conditions using -
- camerawesome 
- the same phone but using the camera app from the device

Result should be the same. 
Note: Flash may occur even during day. That's the hardware that chooses that. 

Let me know

**Comment by Lonely-shang** [comment]
> Hi, We made many tests on this but maybe you are right. Could you make the same test in the same conditions using -
> 
> * camerawesome
> * the same phone but using the camera app from the device
> 
> Result should be the same. Note: Flash may occur even during day. That's the hardware that chooses that.
> 
> Let me know

There are no such issues when using the device camera application on the same phone, only some problems occur when using the camerawesome 

Sorry, it doesn't seem like it's an issue with Android 13
I found a Xiaomi phone, which is also an Android 13, and no such thing happened.

It may be a problem with individual models

**Comment by g-apparence** [comment]
Yes sorry to not be able to do more on this.
Also some applications are still using camera2 and maybe it’s this hardware with cameraX which does this.

That’s the main problem with Android. Every manufacturers have to properly implements the camera.

Kind regards,

———————————

Gautier Siclon
Co-founder | CTO

***@***.***
Apparence.io

**Comment by Lonely-shang** [comment]
> Yes sorry to not be able to do more on this.
> 
> Also some applications are still using camera2 and maybe it’s this hardware with cameraX which does this.
> 
> 
> 
> That’s the main problem with Android. Every manufacturers have to properly implements the camera.
> 
> 
> 
> Kind regards,
> 
> 
> 
> ———————————
> 
> 
> 
> Gautier Siclon
> 
> Co-founder | CTO
> 
> 
> 
> ***@***.***
> 
> Apparence.io
> 
> Le 15 déc. 2023 à 02:40 +0100, Miliky ***@***.***>, a écrit :
> 
> > > Hi, We made many tests on this but maybe you are right. Could you make the same test in the same conditions using -
> 
> > >
> 
> > > • camerawesome
> 
> > > • the same phone but using the camera app from the device
> 
> > >
> 
> > > Result should be the same. Note: Flash may occur even during day. That's the hardware that chooses that.
> 
> > > Let me know
> 
> > There are no such issues when using the device camera application on the same phone, only some problems occur when using the camerawesome
> 
> > Sorry, it doesn't seem like it's an issue with Android 13
> 
> > I found a Xiaomi phone, which is also an Android 13, and no such thing happened.
> 
> > It may be a problem with individual models
> 
> > —
> 
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > You are receiving this because you commented.Message ID: ***@***.***>
> 
> 

Ok, thank you for your reply.

This should be an isolated issue.
I'll keep an eye on it later

I think we can close the issue.
