### ISSUE TITLE
Problem with scan area overlay / google ml kit

### ISSUE THREAD

**Issue by djwinston** [Apparence-io/CamerAwesome#428]
Example of component barcode_preview_overlay.dart has wrong calculate of scan area and pointer position. 
Incorrect calculations

I suppose all calculations of the component have shifted along Y axis

## Steps to Reproduce

- pull CamerAwesome repo
- cd .\example\
- flutter run  -v -t .\lib\preview_overlay_example.dart 

## Expected results
- The barcode must be detected in the scan area
- The scan result should be located under the scanning area

https://docs.page/Apparence-io/camera_awesome/image_analysis/reading_barcodes#scan-area
![image](https://github.com/Apparence-io/CamerAwesome/assets/29452563/861aacc5-c1d4-4d7c-9483-798cf159bade)

## Actual results
- On Android platforms **BarcodeFocusAreaPainter** behaves unpredictably, taking various forms. iOS working correct
- Barcode is detected above the red line along the entire height
- If there are several barcodes nearby the problem is increases

<details>
  <summary>Android</summary>  

https://github.com/Apparence-io/CamerAwesome/assets/29452563/b545e362-2910-4fad-9b4d-917902acf0f8

</details>
<details>
  <summary>iOS</summary>  

https://github.com/Apparence-io/CamerAwesome/assets/29452563/72502d73-b36a-46a9-8c3d-cb15be78b9d2

</details>

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 12Pro*  | *17.2.1*  |
| *OnePlus7* | *GM1901*  | *13*  |

## Flutter version
- version
```
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (11 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```
- flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.2861], locale uk-UA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.8.3)
[√] Android Studio (version 2023.1)
[√] VS Code, 64-bit edition (version 1.85.1)
[√] Connected device (4 available)
[√] Network resources
```

</details>

**Comment by g-apparence** [comment]
Hi

This is a problem within the example. 
I'm sorry, this use the old calculation and the preview widget has been totally remade with some tools to help you convert a point from what you see and what analysis have. (On android for ex analysis image is totally different from what you see). 
That makes thing harder so we made some tools to help you. 

You can check how it is working on the example "ai_analysis_faces.dart" 

```dart
preview!.convertFromImage(
    Offset(element.x.toDouble(), element.y.toDouble()), model.img!)
);
```
- preview comes from the builder 
- it returns an Offset correctly translated according to analysis image, orientation, device
- element is the detected point from analysis

Hope it helps
