### ISSUE TITLE
Change AwesomeCameraModeSelector text

### ISSUE THREAD

**Issue by Natan-hub** [Apparence-io/CamerAwesome#429]
I would like the option in Awesome Camera NodeSelector(state: state) to be able to change the photo and video text for another while maintaining the function of switching between taking a photo and recording a video.

![Captura de Tela 2024-01-03 à(s) 16 22 30](https://github.com/Apparence-io/CamerAwesome/assets/67711835/5a8f5afd-8464-4633-8a41-52c6360e32a7)

**Comment by KnifeLemon** [comment]
you can custom that widget in [awesome_camera_mode_selector.dart](https://github.com/Apparence-io/CamerAwesome/blob/master/lib/src/widgets/awesome_camera_mode_selector.dart)

And using custom widget inside middleContentBuilder

```
middleContentBuilder: (state) {
  return Column(
    children: [
      const Spacer(),
      if (state is PhotoCameraState && state.hasFilters)
        AwesomeFilterWidget(state: state)
      else if (!kIsWeb && Platform.isAndroid)
        AwesomeZoomSelector(state: state),
      /* your custom widget */
    ],
  ),
},
```
