### ISSUE TITLE
Missing release for fix of missing onMediaCapure field

### ISSUE THREAD

**Issue by olenirwing** [Apparence-io/CamerAwesome#480]
Hey @g-apparence, i think you mistakenly forgot to include your [last commit](https://github.com/Apparence-io/CamerAwesome/commit/a6715d98a8511a4c7fe736fbdd61ac97f53c231c) in the 2.0.1, which means that onMediaCapture field is still missing. I'm assuming because the commit came just 30 minutes after you created the release. Please correct me if I'm wrong :)

**Comment by nickolasdeluca** [comment]
Hey @olenirwing, this event you mentioned, was it used to return the picture when the user took the picture? I was wondering why do we have to tap the media button to be able to get the picture just taken.

I understand having to do it if you have your widget set to take multiple pictures, but when it's set to single, it should return the picture right after the user takes the photo.

Am I right to assume this?

**Comment by ryanhanks-bestow** [comment]
@nickolasdeluca @g-apparence, @olenirwing is correct in calling out the mismatch between the version published to pub and what's tagged as 2.0.1 here in this repo.

Can we get a revision bump pushed to correct for this? This was also noticed by @Harpreetcompetent in https://github.com/Apparence-io/CamerAwesome/issues/474 

<img width="804" alt="Screenshot 2024-06-25 at 10 53 15 PM" src="https://github.com/Apparence-io/CamerAwesome/assets/87093311/3ef36598-3a6b-40a7-a392-597cc981f2d1">
<img width="747" alt="Screenshot 2024-06-25 at 10 54 19 PM" src="https://github.com/Apparence-io/CamerAwesome/assets/87093311/0e741108-63b7-49ac-b6d5-c59e4bf3ccf5">

**Comment by ryanhanks-bestow** [comment]
Correction, there's no 2.0.1 tag on this repo, however the version in pubspec and published to pub are both 2.0.1

**Comment by ryanhanks-bestow** [comment]
@g-apparence can we get a release that includes `onMediaCaptureEvent` on `CameraAwesomeBuilder.awesome`?

I started building upon it for lack of understanding of an equivalent approach, but, as mentioned above, `onMediaCaptureEvent` didn't make it into the 2.0.1 that shipped to pub.dev.

Let me know if there's anything I can do, or if there's someone else I can bring into this convo that can help us get this pushed out.

Thanks!

**Comment by xcc3641** [comment]
> @g-apparence can we get a release that includes `onMediaCaptureEvent` on `CameraAwesomeBuilder.awesome`?
> 
> I started building upon it for lack of understanding of an equivalent approach, but, as mentioned above, `onMediaCaptureEvent` didn't make it into the 2.0.1 that shipped to pub.dev.
> 
> Let me know if there's anything I can do, or if there's someone else I can bring into this convo that can help us get this pushed out.
> 
> Thanks!

I just use this to fix it for interim processing.

```
  camerawesome:
    git:
      url: git@github.com:Apparence-io/CamerAwesome.git
      ref: master
```

**Comment by g-apparence** [comment]
It's now released. 
Sorry for delay 🙏🏻

**Comment by ryanhanks-bestow** [comment]
Great to see this and the other updates. Thanks @g-apparence & @tonistayhungrystayfoolish / @bytemaster / @millerf for the PRs

Fyi, I don't think 2.1.0 got tagged as a release here in the repo
