### ISSUE TITLE
Problem with dependency carrousel_slider

### ISSUE THREAD

**Issue by tonistayhungrystayfoolish** [Apparence-io/CamerAwesome#499]
Hi, I updated to flutter 3.24 and show this error: 
'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'. #444
Open
Carousel_slider is Showing two imports #443 

This issue arises due to CarouselController being imported from both package:carousel_slider/carousel_controller.dart and package:flutter/src/material/carousel.dart.

I think that [carousel_slider](https://pub.dev/packages/carousel_slider) which is not maintained anymore.
I will propose fix, replacing carrousel_slider library with another library: carousel_slider_plus it´s a fork  that fix the problem.

**Comment by Nashev** [comment]
https://github.com/Apparence-io/CamerAwesome/pull/502 addressed to fix this

**Comment by g-apparence** [comment]
The new version fix this
