### ISSUE TITLE
CarouselController is imported from both

### ISSUE THREAD

**Issue by AndreyDAraya** [Apparence-io/CamerAwesome#501]
## Steps to Reproduce

Run project with Flutter 3.24.0

## Expected results

Build Done!

## Actual results

Could not build the precompiled application for the device.
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/camerawesome-2.0.1/lib/src/widgets/filters/awesome_filter_selector.dart:3:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Apple* | *iPhone 14 Pro*  | *18*  |

## Your flutter version
3.24.0

**Comment by ohdonpiano** [comment]
android version of the issue:

`Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dev/camerawesome-2.0.1/lib/src/widgets/filters/awesome_filter_selector.dart:3:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'package:flutter/material.dart';
^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:9:1: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
import 'carousel_controller.dart';
^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/camerawesome-2.0.1/lib/src/widgets/filters/awesome_filter_selector.dart:27:42: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
  final CarouselController _controller = CarouselController();
                                         ^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:48:15: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
            : CarouselController() as CarouselControllerImpl,
              ^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/carousel_slider-4.2.1/lib/carousel_slider.dart:62:15: Error: 'CarouselController' is imported from both 'package:carousel_slider/carousel_controller.dart' and 'package:flutter/src/material/carousel.dart'.
            : CarouselController() as CarouselControllerImpl,
              ^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.`

**Comment by Nashev** [comment]
https://github.com/Apparence-io/CamerAwesome/pull/502 addressed to fix it

**Comment by GTechMicah** [comment]
Also #499 and this issue are duplicates if I'm not mistaken

**Comment by GTechMicah** [comment]
And we have three open pull requests to fix this issue:
#502 
#504 
#505 

#505 being the one with the least number of changes

**Comment by Nashev** [comment]
Any way, in master branch you already have similar fix so it just can be released...

**Comment by millerf** [comment]
> Any way, in master branch you already have similar fix so it just can be released...

You must have looked in the wrong repo... The last commit on `master` is 6-months old...

For the record:
- #502 puts the code up to date (removing lint issues), and is a version using `carousel_slider_plus`
- #504 is a fork of the previous reusing `carousel_slider`
- #505 "only" fixes the issues, without fixing the lint issues

**Comment by GTechMicah** [comment]
@millerf fair enough, when can we expect an update on a release that fixes this issue?
@kuhnroyal

**Comment by g-apparence** [comment]
Hi everyone, 
Sorry for not being so active here. 

I am reviewing the code and trying it on iOS and Android. 
Will merge it after that

**Comment by GTechMicah** [comment]
Awesome, thank you for the update!

**Comment by g-apparence** [comment]
Version 2.1.0 published
Thank you all for your help 🙏🏻

**Comment by GTechMicah** [comment]
You're Welcome!

**Comment by GTechMicah** [comment]
@g-apparence #505 is a duplicate of #502 / #504
