### ISSUE TITLE
Image feels streched on Redmi note 5

### ISSUE THREAD

**Issue by HemilTheRebel** [Apparence-io/CamerAwesome#90]
## Steps to Reproduce

Run the sample app on Redmi Note 5

## Expected results
This is the photo taken from my default camera app 

![IMG_20210325_133714](https://user-images.githubusercontent.com/29833486/112439749-822ff780-8d6f-11eb-96ae-9d968203dfb5.jpg)

## Actual results
Here is how it looks in the default example app 
![Screenshot_2021-03-25-13-38-06-810_com apparence camerawesome_example](https://user-images.githubusercontent.com/29833486/112440101-ebb00600-8d6f-11eb-944b-223e284eb2e9.jpg)

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Xiaomi/Redmi* | *Note 5*  | *Android 8.1.0*  |

I tried changing the resolution to 1920x1080 (my phone is 2160x1080). It gives the same result
![Screenshot_2021-03-25-13-43-08-068_com apparence camerawesome_example](https://user-images.githubusercontent.com/29833486/112445210-e6a18580-8d74-11eb-962e-22090093196a.jpg)

**Comment by istornz** [comment]
Closed, please reopen if this bug occurs on latest stable v1.0.0
