### ISSUE TITLE
Preview size cannot be changed or stretched

### ISSUE THREAD

**Issue by sjayadeep** [Apparence-io/CamerAwesome#95]
## Steps to Reproduce

Set photo size as 4000x3000, which is 4:3 resolution photo. But the camera preview is 16:9. 
To make the preview 4:3 I've to crop the preview which will result in viewing a cropped preview of the actual photo.

## Expected results

The preview and photo captured must be same.

## Actual results

Camera Preview ( is in 16:9, but 4:3 is needed)

![WhatsApp Image 2021-05-01 at 11 59 21 PM](https://user-images.githubusercontent.com/6806731/116791776-2547ff80-aada-11eb-8a04-46cb37e9da9b.jpeg)

Photo captured (more data on both sides than preview)
 
![WhatsApp Image 2021-05-01 at 11 59 56 PM](https://user-images.githubusercontent.com/6806731/116791785-2da03a80-aada-11eb-870f-d48ab13e8bd0.jpeg)

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *MI* | *K20 pro*  | *miui 12.0.5 android 10*  |

</details>

**Comment by SrTobi** [comment]
I fixed this by calculating the previewSize in `_initPhotoSize` according to aspect ratio:

```dart
  void _initPhotoSize() {
    widget.photoSize.addListener(() async {
      if (selectedAndroidPhotoSize == null) {
        return;
      }
      final size = widget.photoSize.value;
      selectedAndroidPhotoSize!.value = size;

      var previewSize = size;

      // if previewSize exceeds the max android preview size
      // calculate the biggest possible preview size with same aspect ratio
      if (previewSize.width > 1920 || previewSize.height > 1080) {
        final aspectRatio = size.width / size.height;

        if (aspectRatio > 1920 / 1080) {
          previewSize = Size(1920, 1920 / aspectRatio);
        } else {
          previewSize = Size(aspectRatio * 1080, 1080);
        }
      }
      await CamerawesomePlugin.setPreviewSize(
        previewSize.width.toInt(),
        previewSize.height.toInt(),
      );
      final effectivePreviewSize = await CamerawesomePlugin.getEffectivPreviewSize();
      if (selectedPreviewSize != null) {
        // this future can take time and be called after we disposed
        selectedPreviewSize!.value = effectivePreviewSize;
        if (mounted) {
          setState(() {});
        }
      }
    });
  }
```

**Comment by istornz** [comment]
Closed, please reopen if this bug occurs on latest stable v1.0.0
